try one more.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,9 @@
 #!/bin/bash
+
 indent() {
   sed -u 's/^/       /'
 }
+
 echo "-----> Install ImageMagick"
 
 BUILD_DIR=$1
@@ -10,22 +12,36 @@ VENDOR_DIR="$BUILD_DIR/vendor"
 mkdir -p $VENDOR_DIR
 INSTALL_DIR="$VENDOR_DIR/imagemagick"
 mkdir -p $INSTALL_DIR
-IMAGE_MAGICK_LOCAL_FILE="ImageMagick.tar.gz"
-CACHE_FILE="$CACHE_DIR/$IMAGE_MAGICK_LOCAL_FILE"
-
+IMAGE_MAGICK_VERSION="${IMAGE_MAGICK_VERSION:-6.9.5-8}"
+##CACHE_FILE="$CACHE_DIR/imagemagick-$IMAGE_MAGICK_VERSION.tar.gz"
+CACHE_FILE="$CACHE_DIR/7.0.3-0.tar.gz"
+https://github.com/ImageMagick/ImageMagick/archive/7.0.3-0.tar.gz
 if [ ! -f $CACHE_FILE ]; then
   # install imagemagick
-  
-  tar -xzvf $BUILD_DIR/$IMAGE_MAGICK_LOCAL_FILE -C $INSTALL_DIR
+  IMAGE_MAGICK_FILE="7.0.3-0.tar.gz"
+  IMAGE_MAGICK_DIR="ImageMagick-7.0.3-0"
+  # SSL cert used on imagemagick not recognized by heroku.
+  ##IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
+  IMAGE_MAGICK_URL="https://github.com/ImageMagick/ImageMagick/archive/7.0.3-0.tar.gz"
+  echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
+  wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
+
+  echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
+  if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
+    echo "Error: Unable to download ImageMagick" | indent
+    ls $BUILD_DIR | indent
+    exit 1;
+  fi
+  tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
 
   echo "-----> Building ImageMagick"
-  cd $INSTALL_DIR
+  cd $IMAGE_MAGICK_DIR
   export CPPFLAGS="-I$INSTALL_DIR/include"
   export LDFLAGS="-L$INSTALL_DIR/lib"
   ./configure --prefix=$INSTALL_DIR
   make && make install
   cd ..
-  rm -rf $INSTALL_DIR
+  rm -rf $IMAGE_MAGICK_DIR
 
   # cache for future deploys
   echo "-----> Caching ImageMagick installation"
